Fix deprecated reflection type to string
KristofMorva/laravel-ide-macros pull request #19
Opened 2020-05-28 08:39 UTC by mortenscheel

`\ReflectionType::__toString()` [was deprecated](https://www.php.net/manual/en/reflectionparameter.gettype.php) in PHP 7.1.

This PR fixes the issue by using `\ReflectionNamedType` when the PHP version is >= 7.1.

I've also included a couple of commits with coding standard fixes that are not related to this issue.

2020-05-28 10:53 UTC, KristofMorva requested changes
Thank you for the contribution! It seems like a great way to keep backwards compatibility with PHP 7.0 (even if it's EOL).
There were some smaller code style issues that I have highlighted.

You were able to test your changes before submitting, right? Sadly I don't have any environment set up right now.

2020-05-28 10:53 UTC, KristofMorva commented on src/Console/MacrosCommand.php
> +        } elseif ($returnType instanceof \ReflectionNamedType){
A whitespace is missing before the curly bracket.

2020-05-28 10:53 UTC, KristofMorva commented on src/Console/MacrosCommand.php
> +            $this->write(": \\{$returnType->getName()}");
In other parts of the code, method calls are never inline but appended to the string instead - just for the sake of consistency I think it'd be best to stick to that format.

2020-05-28 17:22 UTC, mortenscheel commented
Hi. I've tested it locally in one of my projects, but I'm only able to test with PHP 7.4.
It would be nice to have proper tests, but I don't know if Testbench would work for something like this?

2020-05-28 17:42 UTC, KristofMorva commented
> 
> 
> Hi. I've tested it locally in one of my projects, but I'm only able to test with PHP 7.4.
> It would be nice to have proper tests, but I don't know if Testbench would work for something like this?

Sadly I'm not familiar with the recent tools and practices in PHP so I couldn't say :/
Nevertheless, if you won't find a great way to test it out extensively, we can release a few feature version with this PR so people can try it out.

2020-06-24 12:54 UTC, mortenscheel commented
Just a status check. Are you happy with the changes I made?

2020-06-26 10:23 UTC, merged

2020-06-26 10:30 UTC, KristofMorva commented
Sorry for the delay. It has been released in https://github.com/KristofMorva/laravel-ide-macros/releases/tag/1.5.0

Thank you for your contribution! :)
Let me know if you experience any issues regarding this solution.

2020-08-22 09:26 UTC, KristofMorva commented
Hello @mortenscheel, it seems to break #21. Could you please make a change which does not use `\` for built-in types?

2020-08-23 16:05 UTC, mortenscheel commented
Hi @KristofMorva 
Sorry about that. It's fixed in #22